name: Deploy App to Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Node.js (with Yarn caching)
    - name: Setup Node & Yarn
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Yarn
      run: npm install -g yarn

    # Step 3: Install dependencies
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    # Step 4: Build the app
    - name: Build the app
      run: yarn build

    # Step 5: Deploy to EC2 via SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:

        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        debug: true
        script: |
          cd /var/www/html/offramp-server-dev
          sudo git -c credential.helper='!f() { echo "username=${{ secrets.GIT_USERNAME }}"; echo "password=${{ secrets.GIT_TOKEN }}"; }; f' pull origin main
          sudo /root/.nvm/versions/node/v22.9.0/bin/yarn install --frozen-lockfile
          sudo /root/.nvm/versions/node/v22.9.0/bin/yarn build
          cp .env ./build
          sudo /root/.nvm/versions/node/v22.9.0/bin/pm2 delete offramp-server-dev
          sudo /root/.nvm/versions/node/v22.9.0/bin/pm2 start npm --name 'offramp-server-dev' -- run start:prod

